# AI Commerce Agent

# AI Product Assistant Agemt
---

In [47]:
import pandas as pd

# df = pd.read_csv(r"C:\Users\lenovo\Downloads\archive\amazon_products.csv")
# categories = pd.read_csv(r"C:\Users\lenovo\Downloads\archive\amazon_categories.csv")
df = pd.read_csv(r"C:\Users\lenovo\Downloads\amazon_products_cleaned.csv")
df.head()

,Unnamed: 0,Product Category,Product Subcategory,Product Name,Product URL,Product Price,Product Rating,Total Ratings,Product Image
0,0,Electronics,Smartphones,"SAMSUNG Galaxy S25 Ultra Cell Phone, 512GB AI ...",https://www.amazon.com/SAMSUNG-Smartphone-Unlo...,"$1,219.99",4.3,247,https://m.media-amazon.com/images/I/61n0lmxP5-...
1,1,Electronics,Smartphones,"SAMSUNG Galaxy A16 5G A Series Cell Phone, Unl...",https://www.amazon.com/SAMSUNG-Unlocked-Smartp...,$174.99,4.2,166,https://m.media-amazon.com/images/I/71KGkQ+KOK...
2,2,Electronics,Smartphones,Tracfone | Motorola Moto g Play 2024 | Locked ...,https://www.amazon.com/Tracfone-Motorola-5000m...,$39.88,4.3,428,https://m.media-amazon.com/images/I/71CxUvG46r...
3,3,Electronics,Smartphones,"SAMSUNG Galaxy S24 FE AI Phone, 128GB Unlocked...",https://www.amazon.com/SAMSUNG-Unlocked-Smartp...,$498.95,4.5,567,https://m.media-amazon.com/images/I/61uakkLoHx...
4,4,Electronics,Smartphones,Moto G 5G | 2024 | Unlocked | Made for US 4/12...,https://www.amazon.com/Moto-Unlocked-128GB-Cam...,$149.99,4.2,"1,677",https://m.media-amazon.com/images/I/71Sbx9zQN3...

In [48]:
# categories.head()

In [55]:
df.isnull().sum()

Unnamed: 0             0
Product Category       1
Product Subcategory    1
Product Name           3
Product URL            1
Product Price          1
Product Rating         1
Total Ratings          3
Product Image          1
dtype: int64

In [ ]:
df = df.dropna()

In [57]:
df.isnull().sum()

Unnamed: 0             0
Product Category       0
Product Subcategory    0
Product Name           0
Product URL            0
Product Price          0
Product Rating         0
Total Ratings          0
Product Image          0
dtype: int64

In [ ]:
df['Product Price'].str.replace('$','').replace(' ','')

0        1,219.99
1          174.99
2           39.88
3          498.95
4          149.99
           ...
42428       139.00
42429       379.00
42430       143.99
42431       168.00
42432       118.99
Name: Product Price, Length: 42430, dtype: str

In [79]:
df['Product Price'] = df['Product Price'].str.replace('$','').str.replace(',','').str.strip()

In [90]:
df['Product Price'] = df['Product Price'].astype(float)

In [104]:
df.head()

,Unnamed: 0,Product Category,Product Subcategory,Product Name,Product URL,Product Price,Product Rating,Total Ratings,Product Image
0,0,Electronics,Smartphones,"SAMSUNG Galaxy S25 Ultra Cell Phone, 512GB AI ...",https://www.amazon.com/SAMSUNG-Smartphone-Unlo...,1219.99,4.3,247,https://m.media-amazon.com/images/I/61n0lmxP5-...
1,1,Electronics,Smartphones,"SAMSUNG Galaxy A16 5G A Series Cell Phone, Unl...",https://www.amazon.com/SAMSUNG-Unlocked-Smartp...,174.99,4.2,166,https://m.media-amazon.com/images/I/71KGkQ+KOK...
2,2,Electronics,Smartphones,Tracfone | Motorola Moto g Play 2024 | Locked ...,https://www.amazon.com/Tracfone-Motorola-5000m...,39.88,4.3,428,https://m.media-amazon.com/images/I/71CxUvG46r...
3,3,Electronics,Smartphones,"SAMSUNG Galaxy S24 FE AI Phone, 128GB Unlocked...",https://www.amazon.com/SAMSUNG-Unlocked-Smartp...,498.95,4.5,567,https://m.media-amazon.com/images/I/61uakkLoHx...
4,4,Electronics,Smartphones,Moto G 5G | 2024 | Unlocked | Made for US 4/12...,https://www.amazon.com/Moto-Unlocked-128GB-Cam...,149.99,4.2,1677,https://m.media-amazon.com/images/I/71Sbx9zQN3...

In [81]:
df.info()

<class 'pandas.DataFrame'>
Index: 42430 entries, 0 to 42432
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           42430 non-null  int64
 1   Product Category     42430 non-null  str
 2   Product Subcategory  42430 non-null  str
 3   Product Name         42430 non-null  str
 4   Product URL          42430 non-null  str
 5   Product Price        42430 non-null  str
 6   Product Rating       42430 non-null  float64
 7   Total Ratings        42430 non-null  str
 8   Product Image        42430 non-null  str
dtypes: float64(1), int64(1), str(7)
memory usage: 38.3 MB

In [82]:
df['Product Rating'] = df['Product Rating'].astype(float)

In [84]:
df['Total Ratings'] = df['Total Ratings'].str.replace(',','').str.strip().astype(int)

In [85]:
df.info()

<class 'pandas.DataFrame'>
Index: 42430 entries, 0 to 42432
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           42430 non-null  int64
 1   Product Category     42430 non-null  str
 2   Product Subcategory  42430 non-null  str
 3   Product Name         42430 non-null  str
 4   Product URL          42430 non-null  str
 5   Product Price        42430 non-null  str
 6   Product Rating       42430 non-null  float64
 7   Total Ratings        42430 non-null  int64
 8   Product Image        42430 non-null  str
dtypes: float64(1), int64(2), str(6)
memory usage: 38.1 MB

In [107]:
# import pandas as pd

# df = pd.read_csv("data/products.csv")

# def search_products(category, budget):
#     results = df[
#         # (df['category_id'].str.contains(category, case=False)) &
#         # (df['price'] <= budget)
#         (df['category_id'] == category) &
#         (df['price'] <= budget)
#     ]
#     return results

def search_products(category, budget):
    results = df[
        (df['Product Name'].str.contains(category, case=False)) &
        (df['Product Price'] <= budget) &
        (df['Product Subcategory'].str.contains('smartphone', case=False))
    ]
    return results

search_products('phone', 10000)

,Unnamed: 0,Product Category,Product Subcategory,Product Name,Product URL,Product Price,Product Rating,Total Ratings,Product Image
0,0,Electronics,Smartphones,"SAMSUNG Galaxy S25 Ultra Cell Phone, 512GB AI ...",https://www.amazon.com/SAMSUNG-Smartphone-Unlo...,1219.99,4.3,247,https://m.media-amazon.com/images/I/61n0lmxP5-...
1,1,Electronics,Smartphones,"SAMSUNG Galaxy A16 5G A Series Cell Phone, Unl...",https://www.amazon.com/SAMSUNG-Unlocked-Smartp...,174.99,4.2,166,https://m.media-amazon.com/images/I/71KGkQ+KOK...
3,3,Electronics,Smartphones,"SAMSUNG Galaxy S24 FE AI Phone, 128GB Unlocked...",https://www.amazon.com/SAMSUNG-Unlocked-Smartp...,498.95,4.5,567,https://m.media-amazon.com/images/I/61uakkLoHx...
7,7,Electronics,Smartphones,Google Pixel Fold - Unlocked Android 5G Smartp...,https://www.amazon.com/Google-Pixel-Fold-Smart...,639.95,3.8,182,https://m.media-amazon.com/images/I/61sOr+Jpqy...
9,9,Electronics,Smartphones,"SAMSUNG Galaxy A35 5G A Series Cell Phone, 128...",https://www.amazon.com/SAMSUNG-A35-Unlocked-Sm...,399.99,4.4,892,https://m.media-amazon.com/images/I/71YwZXmVcE...
11,11,Electronics,Smartphones,"Samsung Galaxy A13 5G Cell Phone, AT&T GSM Unl...",https://www.amazon.com/Galaxy-A13-5G-Smartphon...,88.00,3.9,1547,https://m.media-amazon.com/images/I/61PkHEMqZf...
12,12,Electronics,Smartphones,"Samsung Galaxy S24 Ultra Cell Phone, 512GB AI ...",https://www.amazon.com/SAMSUNG-Smartphone-Unlo...,1078.99,4.5,2718,https://m.media-amazon.com/images/I/71WcjsOVOm...
13,13,Electronics,Smartphones,Google Pixel 8a - Unlocked Android Phone with ...,https://www.amazon.com/Google-Pixel-8a-Unlocke...,399.00,4.3,1063,https://m.media-amazon.com/images/I/71XOyJfGIz...
14,14,Electronics,Smartphones,"Samsung Galaxy A03s Cell Phone, AT&T GSM Unloc...",https://www.amazon.com/Samsung-Unlocked-Smartp...,69.49,3.8,1062,https://m.media-amazon.com/images/I/51m45B3Yy+...
15,15,Electronics,Smartphones,Samsung Galaxy A15 A155M 128GB Dual-SIM GSM Un...,https://www.amazon.com/Samsung-SM-155M-DSN-Unl...,155.70,4.3,979,https://m.media-amazon.com/images/I/515zGEaoze...
17,17,Electronics,Smartphones,Unlocked Cell Phone Pova6 Pro Smartphone 8GB+2...,https://www.amazon.com/fuxinya-Pova6-Pro-Smart...,99.99,5.0,5,https://m.media-amazon.com/images/I/71xuDa6S03...
18,18,Electronics,Smartphones,"Apple iPhone 13, 128GB, Blue - Unlocked (Renewed)",https://www.amazon.com/Apple-iPhone-13-128GB-B...,299.99,4.0,14764,https://m.media-amazon.com/images/I/71MKNCEgE6...
22,22,Electronics,Smartphones,"DOOGEE Blade GT AI 5G Rugged Phone Unlocked,LE...",https://www.amazon.com/DOOGEE-Blade-GT-Ultra-T...,329.99,4.4,50,https://m.media-amazon.com/images/I/71abuijqqh...
24,24,Electronics,Smartphones,"HMD Vibe | Verizon, T-Mobile, AT&T | Unlocked ...",https://www.amazon.com/HMD-T-Mobile-Unlocked-S...,102.99,4.2,51,https://m.media-amazon.com/images/I/7151w0t0AJ...
25,25,Electronics,Smartphones,"NUU N10 Basic Cell Phone for T-Mobile, Mint, M...",https://www.amazon.com/NUU-T-Mobile-Teenagers-...,99.99,4.1,210,https://m.media-amazon.com/images/I/71sP4qAvqz...
26,26,Electronics,Smartphones,Motorola G85 5G 12GB 256GB | pOLED 120 Hz | 50...,https://www.amazon.com/Motorola-5000mah-Batter...,227.20,4.3,292,https://m.media-amazon.com/images/I/71IZFZGzOz...
28,28,Electronics,Smartphones,"SAMSUNG Galaxy Z Fold 6 AI Cell Phone, 512GB U...",https://www.amazon.com/SAMSUNG-Smartphone-Hand...,1549.97,4.3,284,https://m.media-amazon.com/images/I/61896OtgvG...
29,29,Electronics,Smartphones,Samsung Galaxy A05 A055M 64GB Dual-SIM GSM Unl...,https://www.amazon.com/Samsung-Dual-SIM-Unlock...,89.72,4.2,472,https://m.media-amazon.com/images/I/71+hnEbedd...
30,30,Electronics,Smartphones,"Samsung Galaxy S22 Smartphone, Factory Unlocke...",https://www.amazon.com/Samsung-Smartphone-Unlo...,258.44,4.0,2948,https://m.media-amazon.com/images/I/61M4ndNetD...

In [108]:
df = pd.read_csv(r"C:\Users\lenovo\Downloads\archive\amazon_products.csv")

In [109]:
df.head()

,asin,title,imgUrl,productURL,stars,reviews,price,listPrice,category_id,isBestSeller,boughtInLastMonth
0,B014TMV5YE,"Sion Softside Expandable Roller Luggage, Black...",https://m.media-amazon.com/images/I/815dLQKYIY...,https://www.amazon.com/dp/B014TMV5YE,4.5,0,139.99,0.00,104,False,2000
1,B07GDLCQXV,Luggage Sets Expandable PC+ABS Durable Suitcas...,https://m.media-amazon.com/images/I/81bQlm7vf6...,https://www.amazon.com/dp/B07GDLCQXV,4.5,0,169.99,209.99,104,False,1000
2,B07XSCCZYG,Platinum Elite Softside Expandable Checked Lug...,https://m.media-amazon.com/images/I/71EA35zvJB...,https://www.amazon.com/dp/B07XSCCZYG,4.6,0,365.49,429.99,104,False,300
3,B08MVFKGJM,Freeform Hardside Expandable with Double Spinn...,https://m.media-amazon.com/images/I/91k6NYLQyI...,https://www.amazon.com/dp/B08MVFKGJM,4.6,0,291.59,354.37,104,False,400
4,B01DJLKZBA,Winfield 2 Hardside Expandable Luggage with Sp...,https://m.media-amazon.com/images/I/61NJoaZcP9...,https://www.amazon.com/dp/B01DJLKZBA,4.5,0,174.99,309.99,104,False,400

In [ ]:
def search_products(category, budget):
    results = df[
        (df['title'].str.contains(category, case=False)) &
        (df['price'] <= budget)
    ]
    return results

search_products('men bag', 10000)

,asin,title,imgUrl,productURL,stars,reviews,price,listPrice,category_id,isBestSeller,boughtInLastMonth
6710,B0BC2XN8Q7,Jeans for Women Baggy Cargo Pants Men Y2K Para...,https://m.media-amazon.com/images/I/61I3by10Oe...,https://www.amazon.com/dp/B0BC2XN8Q7,3.9,0,39.85,0.00,110,False,0
41932,B0B2WD65GW,Creative Skull Dino Keychain for Men Bags Back...,https://m.media-amazon.com/images/I/61JXG6885z...,https://www.amazon.com/dp/B0B2WD65GW,4.4,0,11.99,12.99,112,False,50
221084,B0BYD3WRNS,Konelia Travel Bag Convertible Garment Weekend...,https://m.media-amazon.com/images/I/81lnoOMMFl...,https://www.amazon.com/dp/B0BYD3WRNS,4.3,6,34.99,43.99,108,False,0
221103,B0CBQPBXDL,Charms for Bogg Bag Bag Beach Tote Bag Rubber ...,https://m.media-amazon.com/images/I/71m7J0v0Hw...,https://www.amazon.com/dp/B0CBQPBXDL,2.8,5,7.99,0.00,108,False,50
221822,B0CBQQXBQ4,Charms for Bogg Bag Beach Tote Bag Rubber Beac...,https://m.media-amazon.com/images/I/616vu2xKk0...,https://www.amazon.com/dp/B0CBQQXBQ4,5.0,3,7.99,0.00,108,False,0
...,...,...,...,...,...,...,...,...,...,...,...
1394904,B0BWYCL6Z4,"2 Pcs Luggage Tag for Suitcases, Cute Leather ...",https://m.media-amazon.com/images/I/71gZIJT4Md...,https://www.amazon.com/dp/B0BWYCL6Z4,4.8,0,7.29,0.00,105,False,800
1396979,B0C4DV9QXM,"Rimilak 10 Pack PVC Luggage Tags for Suitcase,...",https://m.media-amazon.com/images/I/81Fp-dwUEe...,https://www.amazon.com/dp/B0C4DV9QXM,4.9,0,5.99,0.00,105,False,100
1397464,B09P341625,6 Pieces Makeup Bag Set Travel Cosmetic Bag Co...,https://m.media-amazon.com/images/I/81lDWo1Fe2...,https://www.amazon.com/dp/B09P341625,4.8,0,22.99,24.99,105,False,0
1397909,B0C8MGVLV1,Hsxnam 2 Pack PU Leather Luggage Tags for Suit...,https://m.media-amazon.com/images/I/81zzLukFHR...,https://www.amazon.com/dp/B0C8MGVLV1,0.0,0,6.99,0.00,105,False,100
1404151,B0C2V5T5PD,"XIQIGUGUA 2 Pack Luggage Tag for Suitcases, Ho...",https://m.media-amazon.com/images/I/71UYtL9xBz...,https://www.amazon.com/dp/B0C2V5T5PD,4.5,0,11.99,0.00,105,False,0

---
---
---
---

In [113]:
import os
os.listdir('resources')

['Cars Datasets 2025.csv',
 'Flipkart_trending_mobils_feb_2026.csv',
 'laptop.csv',
 'laptops data details.txt',
 'Mobiles Dataset (2025).csv']

# Mobile phones data produced in <= 2025

In [121]:
# Mobile phones data produced in <= 2025
phones = pd.read_csv('resources/Mobiles Dataset (2025).csv', encoding='latin1')
phones.head()

,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (Pakistan),Launched Price (India),Launched Price (China),Launched Price (USA),Launched Price (Dubai),Launched Year
0,Apple,iPhone 16 128GB,174g,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,"PKR 224,999","INR 79,999","CNY 5,799",USD 799,"AED 2,799",2024
1,Apple,iPhone 16 256GB,174g,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,"PKR 234,999","INR 84,999","CNY 6,099",USD 849,"AED 2,999",2024
2,Apple,iPhone 16 512GB,174g,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,"PKR 244,999","INR 89,999","CNY 6,499",USD 899,"AED 3,199",2024
3,Apple,iPhone 16 Plus 128GB,203g,6GB,12MP,48MP,A17 Bionic,"4,200mAh",6.7 inches,"PKR 249,999","INR 89,999","CNY 6,199",USD 899,"AED 3,199",2024
4,Apple,iPhone 16 Plus 256GB,203g,6GB,12MP,48MP,A17 Bionic,"4,200mAh",6.7 inches,"PKR 259,999","INR 94,999","CNY 6,499",USD 949,"AED 3,399",2024

## Preprocessing

In [124]:
phones.columns

Index(['Company Name', 'Model Name', 'Mobile Weight', 'RAM', 'Front Camera',
       'Back Camera', 'Processor', 'Battery Capacity', 'Screen Size',
       'Launched Price (Pakistan)', 'Launched Price (India)',
       'Launched Price (China)', 'Launched Price (USA)',
       'Launched Price (Dubai)', 'Launched Year'],
      dtype='str')

In [130]:
phones.drop(['Launched Price (India)','Launched Price (China)','Launched Price (Pakistan)','Launched Price (Dubai)'], axis=1, inplace=True)

In [131]:
phones.head(3)

,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (USA),Launched Year
0,Apple,iPhone 16 128GB,174g,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,USD 799,2024
1,Apple,iPhone 16 256GB,174g,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,USD 849,2024
2,Apple,iPhone 16 512GB,174g,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,USD 899,2024

In [139]:
phones['Launched Price (USA)'] = phones['Launched Price (USA)'].str.replace('USD','').str.replace(',','').str.strip().astype(float)

phones.head()

,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (USA),Launched Year
0,Apple,iPhone 16 128GB,174g,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,799.0,2024
1,Apple,iPhone 16 256GB,174g,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,849.0,2024
2,Apple,iPhone 16 512GB,174g,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,899.0,2024
3,Apple,iPhone 16 Plus 128GB,203g,6GB,12MP,48MP,A17 Bionic,"4,200mAh",6.7 inches,899.0,2024
4,Apple,iPhone 16 Plus 256GB,203g,6GB,12MP,48MP,A17 Bionic,"4,200mAh",6.7 inches,949.0,2024

In [141]:
phones['Mobile Weight'] = phones['Mobile Weight'].str.replace('g','').str.strip().astype(float)

In [ ]:
# phones['Camera'] = phones['Back Camera'] + ' | ' + phones['Front Camera'] + ' Front Camera'
# phones.drop("Camera", inplace=True, axis=1)

In [160]:
phones.head()

,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (USA),Launched Year
0,Apple,iPhone 16 128GB,174.0,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,799.0,2024
1,Apple,iPhone 16 256GB,174.0,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,849.0,2024
2,Apple,iPhone 16 512GB,174.0,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,899.0,2024
3,Apple,iPhone 16 Plus 128GB,203.0,6GB,12MP,48MP,A17 Bionic,"4,200mAh",6.7 inches,899.0,2024
4,Apple,iPhone 16 Plus 256GB,203.0,6GB,12MP,48MP,A17 Bionic,"4,200mAh",6.7 inches,949.0,2024

In [165]:
phones['Company Name'] + ' ' +phones['Model Name']

0             Apple iPhone 16 128GB
1             Apple iPhone 16 256GB
2             Apple iPhone 16 512GB
3        Apple iPhone 16 Plus 128GB
4        Apple iPhone 16 Plus 256GB
                   ...
925               Poco Pad 5G 128GB
926               Poco Pad 5G 256GB
927    Samsung Galaxy Z Fold6 256GB
928    Samsung Galaxy Z Fold6 512GB
929      Samsung Galaxy Z Fold6 1TB
Length: 930, dtype: str

In [166]:
phones

,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (USA),Launched Year
0,Apple,iPhone 16 128GB,174.0,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,799.0,2024
1,Apple,iPhone 16 256GB,174.0,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,849.0,2024
2,Apple,iPhone 16 512GB,174.0,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,899.0,2024
3,Apple,iPhone 16 Plus 128GB,203.0,6GB,12MP,48MP,A17 Bionic,"4,200mAh",6.7 inches,899.0,2024
4,Apple,iPhone 16 Plus 256GB,203.0,6GB,12MP,48MP,A17 Bionic,"4,200mAh",6.7 inches,949.0,2024
...,...,...,...,...,...,...,...,...,...,...,...
925,Poco,Pad 5G 128GB,571.0,8GB,8MP,8MP,Snapdragon 7s Gen 2,"10,000mAh",12.1 inches,280.0,2024
926,Poco,Pad 5G 256GB,571.0,8GB,8MP,8MP,Snapdragon 7s Gen 2,"10,000mAh",12.1 inches,300.0,2024
927,Samsung,Galaxy Z Fold6 256GB,239.0,12GB,"10MP, 4MP (UDC)",50MP,Snapdragon 8 Gen 3,4400mAh,7.6 inches,1899.0,2024
928,Samsung,Galaxy Z Fold6 512GB,239.0,12GB,"10MP, 4MP (UDC)",50MP,Snapdragon 8 Gen 3,4400mAh,7.6 inches,1719.0,2024
929,Samsung,Galaxy Z Fold6 1TB,239.0,12GB,"10MP, 4MP (UDC)",50MP,Snapdragon 8 Gen 3,4400mAh,7.6 inches,2259.0,2024

In [164]:
phones.drop('Name', axis=1, inplace = True)

In [172]:
phones.isnull().sum()

Company Name            0
Model Name              0
Mobile Weight           0
RAM                     0
Front Camera            0
Back Camera             0
Processor               0
Battery Capacity        0
Screen Size             0
Launched Price (USA)    0
Launched Year           0
dtype: int64

In [173]:
phones.info()

<class 'pandas.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Company Name          930 non-null    str
 1   Model Name            930 non-null    str
 2   Mobile Weight         930 non-null    float64
 3   RAM                   930 non-null    str
 4   Front Camera          930 non-null    str
 5   Back Camera           930 non-null    str
 6   Processor             930 non-null    str
 7   Battery Capacity      930 non-null    str
 8   Screen Size           930 non-null    str
 9   Launched Price (USA)  930 non-null    float64
 10  Launched Year         930 non-null    int64
dtypes: float64(2), int64(1), str(8)
memory usage: 145.7 KB

---

# Mobile phones data produced in 2026

In [146]:
# Mobile phones data produced in 2026
phones26 = pd.read_csv('resources/Flipkart_trending_mobils_feb_2026.csv')
phones26.head()

,Unnamed: 0,name,image,rating,warrenty,display,camera,processor,ram and rom,price
0,0,"Samsung Galaxy F70e 5G (Limelight Green, 128 GB)","src=""https://rukminim2.flixcart.com/image/312/...","2,08,961 Ratings & 6,706 Reviews",NaN,17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,6000 mAh Li-ion Battery,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,"₹11,749"
1,1,"Apple iPhone 16 (White, 128 GB)","src=""https://rukminim2.flixcart.com/image/312/...","17,642 Ratings & 944 Reviews",NaN,15.49 cm (6.1 inch) Super Retina XDR Display,48MP + 12MP | 12MP Front Camera,"A18 Chip, 6 Core Processor Processor",128 GB ROM,"₹64,900"
2,2,"MOTOROLA g57 power 5G (Pantone Fluidity, 128 GB)","src=""https://rukminim2.flixcart.com/image/312/...","2,08,961 Ratings & 6,706 Reviews",NaN,17.07 cm (6.72 inch) Full HD+ Display,50MP + 8MP | 8MP Front Camera,7000 mAh Battery,8 GB RAM | 128 GB ROM,"₹13,999"
3,3,"Apple iPhone 16 (Black, 128 GB)","src=""https://rukminim2.flixcart.com/image/312/...","45,190 Ratings & 1,306 Reviews",NaN,15.49 cm (6.1 inch) Super Retina XDR Display,48MP + 12MP | 12MP Front Camera,"A18 Chip, 6 Core Processor Processor",128 GB ROM,"₹64,900"
4,4,vivo T4 Lite 5G Charger in the Box (Titanium G...,"src=""https://rukminim2.flixcart.com/image/312/...","2,08,961 Ratings & 6,706 Reviews",NaN,17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 5MP Front Camera,6000 mAh Battery,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,"₹10,999"

## preprocessing

In [168]:
c = phones26.columns
c

Index(['Unnamed: 0', 'name', 'image', 'rating', 'warrenty', 'display',
       'camera', 'processor', 'ram and rom', 'price'],
      dtype='str')

In [169]:
phones26.drop(c[0], axis=1, inplace=True)
phones26.head(1)

,name,image,rating,warrenty,display,camera,processor,ram and rom,price
0,"Samsung Galaxy F70e 5G (Limelight Green, 128 GB)","src=""https://rukminim2.flixcart.com/image/312/...","2,08,961 Ratings & 6,706 Reviews",NaN,17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,6000 mAh Li-ion Battery,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,"₹11,749"

In [170]:
phones26.drop('warrenty', axis=1, inplace=True)
phones26.head(1)

,name,image,rating,display,camera,processor,ram and rom,price
0,"Samsung Galaxy F70e 5G (Limelight Green, 128 GB)","src=""https://rukminim2.flixcart.com/image/312/...","2,08,961 Ratings & 6,706 Reviews",17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,6000 mAh Li-ion Battery,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,"₹11,749"

In [171]:
phones26.drop('rating', axis=1, inplace=True)
phones26.drop('image', axis=1, inplace=True)

phones26.head(1)

,name,display,camera,processor,ram and rom,price
0,"Samsung Galaxy F70e 5G (Limelight Green, 128 GB)",17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,6000 mAh Li-ion Battery,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,"₹11,749"

In [174]:
phones.head(1)

,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (USA),Launched Year
0,Apple,iPhone 16 128GB,174.0,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,799.0,2024

In [185]:
phones26['name'].str.split(' ', n=1).str.get(0)

0       Samsung
1         Apple
2      MOTOROLA
3         Apple
4          vivo
         ...
835         hmd
836        vivo
837    MOTOROLA
838      realme
839    Kechaoda
Name: name, Length: 840, dtype: object

In [186]:
phones26.insert(loc=0, column='Company Name', value=phones26['name'].str.split(' ', n=1).str.get(0))

In [187]:
phones26

,Company Name,name,display,camera,processor,ram and rom,price
0,Samsung,"Samsung Galaxy F70e 5G (Limelight Green, 128 GB)",17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,6000 mAh Li-ion Battery,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,"₹11,749"
1,Apple,"Apple iPhone 16 (White, 128 GB)",15.49 cm (6.1 inch) Super Retina XDR Display,48MP + 12MP | 12MP Front Camera,"A18 Chip, 6 Core Processor Processor",128 GB ROM,"₹64,900"
2,MOTOROLA,"MOTOROLA g57 power 5G (Pantone Fluidity, 128 GB)",17.07 cm (6.72 inch) Full HD+ Display,50MP + 8MP | 8MP Front Camera,7000 mAh Battery,8 GB RAM | 128 GB ROM,"₹13,999"
3,Apple,"Apple iPhone 16 (Black, 128 GB)",15.49 cm (6.1 inch) Super Retina XDR Display,48MP + 12MP | 12MP Front Camera,"A18 Chip, 6 Core Processor Processor",128 GB ROM,"₹64,900"
4,vivo,vivo T4 Lite 5G Charger in the Box (Titanium G...,17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 5MP Front Camera,6000 mAh Battery,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,"₹10,999"
...,...,...,...,...,...,...,...
835,hmd,hmd 110 Dual Sim Keypad Phone with Built-in Sc...,5.08 cm (2 inch) NA Display,0.2MP Rear Camera,1000 mAh Battery,4 MB RAM | 4 MB ROM,"₹1,189"
836,vivo,"vivo Y19s 5G (Majestic Green, 64.0 GB)",17.12 cm (6.74 inch) Display,13MP + 0.08MP | 5MP Front Camera,6000 mAh Battery,4 GB RAM | 64.0 GB ROM | Expandable Upto 2 TB,"₹12,499"
837,MOTOROLA,"MOTOROLA Edge 70 (PANTONE Lily Pad, 256 GB)",17.02 cm (6.7 inch) Display,50MP + 50MP | 50MP Front Camera,5000 mAh Battery,8 GB RAM | 256 GB ROM,"₹32,999"
838,realme,"realme P3 Ultra 5G (Neptune Blue, 128 GB)",17.35 cm (6.83 inch) Display,50MP + 8MP | 16MP Front Camera,6000 mAh Battery,8 GB RAM | 128 GB ROM,"₹23,999"
839,Kechaoda,Kechaoda A27,1.68 cm (0.66 inch) QVGA Display,0MP | 0MP Front Camera,800 mAh Battery,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB,₹899

In [188]:
phones26['name'].str.split(' ', n=1).str.get(1)

0               Galaxy F70e 5G (Limelight Green, 128 GB)
1                              iPhone 16 (White, 128 GB)
2                g57 power 5G (Pantone Fluidity, 128 GB)
3                              iPhone 16 (Black, 128 GB)
4      T4 Lite 5G Charger in the Box (Titanium Gold, ...
                             ...
835    110 Dual Sim Keypad Phone with Built-in Scan &...
836                    Y19s 5G (Majestic Green, 64.0 GB)
837                   Edge 70 (PANTONE Lily Pad, 256 GB)
838                   P3 Ultra 5G (Neptune Blue, 128 GB)
839                                                  A27
Name: name, Length: 840, dtype: object

In [189]:
phones26.insert(loc=1, column='Model Name', value=phones26['name'].str.split(' ', n=1).str.get(1))
phones26.head(2)

,Company Name,Model Name,name,display,camera,processor,ram and rom,price
0,Samsung,"Galaxy F70e 5G (Limelight Green, 128 GB)","Samsung Galaxy F70e 5G (Limelight Green, 128 GB)",17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,6000 mAh Li-ion Battery,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,"₹11,749"
1,Apple,"iPhone 16 (White, 128 GB)","Apple iPhone 16 (White, 128 GB)",15.49 cm (6.1 inch) Super Retina XDR Display,48MP + 12MP | 12MP Front Camera,"A18 Chip, 6 Core Processor Processor",128 GB ROM,"₹64,900"

In [ ]:
phones26.drop('name', axis=1, inplace=True)
phones26.head(3)

,Company Name,Model Name,display,camera,processor,ram and rom,price
0,Samsung,"Galaxy F70e 5G (Limelight Green, 128 GB)",17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,6000 mAh Li-ion Battery,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,"₹11,749"
1,Apple,"iPhone 16 (White, 128 GB)",15.49 cm (6.1 inch) Super Retina XDR Display,48MP + 12MP | 12MP Front Camera,"A18 Chip, 6 Core Processor Processor",128 GB ROM,"₹64,900"
2,MOTOROLA,"g57 power 5G (Pantone Fluidity, 128 GB)",17.07 cm (6.72 inch) Full HD+ Display,50MP + 8MP | 8MP Front Camera,7000 mAh Battery,8 GB RAM | 128 GB ROM,"₹13,999"

In [192]:
phones.head(2)

,Company Name,Model Name,Mobile Weight,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (USA),Launched Year
0,Apple,iPhone 16 128GB,174.0,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,799.0,2024
1,Apple,iPhone 16 256GB,174.0,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,849.0,2024

In [198]:
phones26['camera'].str.split('|', n=1).str.get(0).str.strip()

0             50MP + 2MP
1            48MP + 12MP
2             50MP + 8MP
3            48MP + 12MP
4             50MP + 2MP
             ...
835    0.2MP Rear Camera
836        13MP + 0.08MP
837          50MP + 50MP
838           50MP + 8MP
839                  0MP
Name: camera, Length: 840, dtype: object

In [199]:
phones26['Back Camera'] = phones26['camera'].str.split('|', n=1).str.get(0).str.strip()
phones26.head(2)

,Company Name,Model Name,display,camera,processor,ram and rom,price,Back Camera
0,Samsung,"Galaxy F70e 5G (Limelight Green, 128 GB)",17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,6000 mAh Li-ion Battery,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,"₹11,749",50MP + 2MP
1,Apple,"iPhone 16 (White, 128 GB)",15.49 cm (6.1 inch) Super Retina XDR Display,48MP + 12MP | 12MP Front Camera,"A18 Chip, 6 Core Processor Processor",128 GB ROM,"₹64,900",48MP + 12MP

In [201]:
phones26['camera'].str.split('|', n=1).str.get(1).str.replace('Front Camera','').str.strip()

0       8MP
1      12MP
2       8MP
3      12MP
4       5MP
       ...
835     NaN
836     5MP
837    50MP
838    16MP
839     0MP
Name: camera, Length: 840, dtype: object

In [202]:
phones26['Front Camera'] = phones26['camera'].str.split('|', n=1).str.get(1).str.replace('Front Camera','').str.strip()
phones26.head(2)

,Company Name,Model Name,display,camera,processor,ram and rom,price,Back Camera,Front Camera
0,Samsung,"Galaxy F70e 5G (Limelight Green, 128 GB)",17.12 cm (6.74 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,6000 mAh Li-ion Battery,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,"₹11,749",50MP + 2MP,8MP
1,Apple,"iPhone 16 (White, 128 GB)",15.49 cm (6.1 inch) Super Retina XDR Display,48MP + 12MP | 12MP Front Camera,"A18 Chip, 6 Core Processor Processor",128 GB ROM,"₹64,900",48MP + 12MP,12MP

In [ ]:
phones.drop('Mobile Weight', axis=1, inplace=True)

In [203]:
phones26.drop('camera', axis=1, inplace=True)

In [214]:
phones.head(1)

,Company Name,Model Name,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (USA),Launched Year
0,Apple,iPhone 16 128GB,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,799.0,2024

In [208]:
phones26.head(1)

,Company Name,Model Name,display,processor,ram and rom,price,Back Camera,Front Camera
0,Samsung,"Galaxy F70e 5G (Limelight Green, 128 GB)",17.12 cm (6.74 inch) HD+ Display,6000 mAh Li-ion Battery,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,"₹11,749",50MP + 2MP,8MP

In [215]:
phones26['Battery Capacity'] = 0
phones26['Launched Year'] = 0

In [216]:
phones26.columns

Index(['Company Name', 'Model Name', 'display', 'processor', 'ram and rom',
       'price', 'Back Camera', 'Front Camera', 'Battery Capacity',
       'Launched Year'],
      dtype='str')

In [219]:
phones26 = phones26[['Company Name','Model Name', 'ram and rom','Front Camera','Back Camera','processor','Battery Capacity', 'display', 'price','Launched Year']]

In [220]:
phones26.head()

,Company Name,Model Name,ram and rom,Front Camera,Back Camera,processor,Battery Capacity,display,price,Launched Year
0,Samsung,"Galaxy F70e 5G (Limelight Green, 128 GB)",4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,8MP,50MP + 2MP,6000 mAh Li-ion Battery,0,17.12 cm (6.74 inch) HD+ Display,"₹11,749",0
1,Apple,"iPhone 16 (White, 128 GB)",128 GB ROM,12MP,48MP + 12MP,"A18 Chip, 6 Core Processor Processor",0,15.49 cm (6.1 inch) Super Retina XDR Display,"₹64,900",0
2,MOTOROLA,"g57 power 5G (Pantone Fluidity, 128 GB)",8 GB RAM | 128 GB ROM,8MP,50MP + 8MP,7000 mAh Battery,0,17.07 cm (6.72 inch) Full HD+ Display,"₹13,999",0
3,Apple,"iPhone 16 (Black, 128 GB)",128 GB ROM,12MP,48MP + 12MP,"A18 Chip, 6 Core Processor Processor",0,15.49 cm (6.1 inch) Super Retina XDR Display,"₹64,900",0
4,vivo,"T4 Lite 5G Charger in the Box (Titanium Gold, ...",4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,5MP,50MP + 2MP,6000 mAh Battery,0,17.12 cm (6.74 inch) HD+ Display,"₹10,999",0

In [222]:
print(phones.columns)
print('_'*100)
print(phones26.columns)

Index(['Company Name', 'Model Name', 'RAM', 'Front Camera', 'Back Camera',
       'Processor', 'Battery Capacity', 'Screen Size', 'Launched Price (USA)',
       'Launched Year'],
      dtype='str')
____________________________________________________________________________________________________
Index(['Company Name', 'Model Name', 'ram and rom', 'Front Camera',
       'Back Camera', 'processor', 'Battery Capacity', 'display', 'price',
       'Launched Year'],
      dtype='str')

In [223]:
phones26.columns = phones.columns

In [224]:
phones26.columns

Index(['Company Name', 'Model Name', 'RAM', 'Front Camera', 'Back Camera',
       'Processor', 'Battery Capacity', 'Screen Size', 'Launched Price (USA)',
       'Launched Year'],
      dtype='str')

In [225]:
phones26.head()

,Company Name,Model Name,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Launched Price (USA),Launched Year
0,Samsung,"Galaxy F70e 5G (Limelight Green, 128 GB)",4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,8MP,50MP + 2MP,6000 mAh Li-ion Battery,0,17.12 cm (6.74 inch) HD+ Display,"₹11,749",0
1,Apple,"iPhone 16 (White, 128 GB)",128 GB ROM,12MP,48MP + 12MP,"A18 Chip, 6 Core Processor Processor",0,15.49 cm (6.1 inch) Super Retina XDR Display,"₹64,900",0
2,MOTOROLA,"g57 power 5G (Pantone Fluidity, 128 GB)",8 GB RAM | 128 GB ROM,8MP,50MP + 8MP,7000 mAh Battery,0,17.07 cm (6.72 inch) Full HD+ Display,"₹13,999",0
3,Apple,"iPhone 16 (Black, 128 GB)",128 GB ROM,12MP,48MP + 12MP,"A18 Chip, 6 Core Processor Processor",0,15.49 cm (6.1 inch) Super Retina XDR Display,"₹64,900",0
4,vivo,"T4 Lite 5G Charger in the Box (Titanium Gold, ...",4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,5MP,50MP + 2MP,6000 mAh Battery,0,17.12 cm (6.74 inch) HD+ Display,"₹10,999",0

In [227]:
phones.rename(columns={'Launched Price (USA)':'Price'}, inplace=True)

In [228]:
phones26.columns = phones.columns

In [ ]:
# Convert prices into USD
phones26['Price'].str.replace('₹','').str.replace(',','').str.strip().astype(float) *0.01

0      117.49
1      649.00
2      139.99
3      649.00
4      109.99
        ...
835     11.89
836    124.99
837    329.99
838    239.99
839      8.99
Name: Price, Length: 840, dtype: float64

In [234]:
phones26['Price'] = phones26['Price'].str.replace('₹','').str.replace(',','').str.strip().astype(float) *0.01

In [235]:
phones26.head()

,Company Name,Model Name,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Price,Launched Year
0,Samsung,"Galaxy F70e 5G (Limelight Green, 128 GB)",4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,8MP,50MP + 2MP,6000 mAh Li-ion Battery,0,17.12 cm (6.74 inch) HD+ Display,117.49,0
1,Apple,"iPhone 16 (White, 128 GB)",128 GB ROM,12MP,48MP + 12MP,"A18 Chip, 6 Core Processor Processor",0,15.49 cm (6.1 inch) Super Retina XDR Display,649.00,0
2,MOTOROLA,"g57 power 5G (Pantone Fluidity, 128 GB)",8 GB RAM | 128 GB ROM,8MP,50MP + 8MP,7000 mAh Battery,0,17.07 cm (6.72 inch) Full HD+ Display,139.99,0
3,Apple,"iPhone 16 (Black, 128 GB)",128 GB ROM,12MP,48MP + 12MP,"A18 Chip, 6 Core Processor Processor",0,15.49 cm (6.1 inch) Super Retina XDR Display,649.00,0
4,vivo,"T4 Lite 5G Charger in the Box (Titanium Gold, ...",4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,5MP,50MP + 2MP,6000 mAh Battery,0,17.12 cm (6.74 inch) HD+ Display,109.99,0

In [238]:
mobile_phones = pd.concat([phones,phones26], ignore_index=True)
mobile_phones

,Company Name,Model Name,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Price,Launched Year
0,Apple,iPhone 16 128GB,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,799.00,2024
1,Apple,iPhone 16 256GB,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,849.00,2024
2,Apple,iPhone 16 512GB,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,899.00,2024
3,Apple,iPhone 16 Plus 128GB,6GB,12MP,48MP,A17 Bionic,"4,200mAh",6.7 inches,899.00,2024
4,Apple,iPhone 16 Plus 256GB,6GB,12MP,48MP,A17 Bionic,"4,200mAh",6.7 inches,949.00,2024
...,...,...,...,...,...,...,...,...,...,...
1765,hmd,110 Dual Sim Keypad Phone with Built-in Scan &...,4 MB RAM | 4 MB ROM,NaN,0.2MP Rear Camera,1000 mAh Battery,0,5.08 cm (2 inch) NA Display,11.89,0
1766,vivo,"Y19s 5G (Majestic Green, 64.0 GB)",4 GB RAM | 64.0 GB ROM | Expandable Upto 2 TB,5MP,13MP + 0.08MP,6000 mAh Battery,0,17.12 cm (6.74 inch) Display,124.99,0
1767,MOTOROLA,"Edge 70 (PANTONE Lily Pad, 256 GB)",8 GB RAM | 256 GB ROM,50MP,50MP + 50MP,5000 mAh Battery,0,17.02 cm (6.7 inch) Display,329.99,0
1768,realme,"P3 Ultra 5G (Neptune Blue, 128 GB)",8 GB RAM | 128 GB ROM,16MP,50MP + 8MP,6000 mAh Battery,0,17.35 cm (6.83 inch) Display,239.99,0
1769,Kechaoda,A27,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB,0MP,0MP,800 mAh Battery,0,1.68 cm (0.66 inch) QVGA Display,8.99,0

In [240]:
mobile_phones.info()

<class 'pandas.DataFrame'>
RangeIndex: 1770 entries, 0 to 1769
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company Name      1770 non-null   object
 1   Model Name        1770 non-null   object
 2   RAM               1770 non-null   str
 3   Front Camera      1546 non-null   object
 4   Back Camera       1770 non-null   object
 5   Processor         1767 non-null   str
 6   Battery Capacity  1770 non-null   object
 7   Screen Size       1770 non-null   str
 8   Price             1770 non-null   float64
 9   Launched Year     1770 non-null   int64
dtypes: float64(1), int64(1), object(5), str(3)
memory usage: 232.2+ KB

Storing the final dataframe

In [241]:
mobile_phones.to_csv('mobile_phones.csv', index=False)

---

# laptops data

In [251]:
# laptops data
laptops = pd.read_csv('resources/laptop.csv')
laptops.head()

,Unnamed: 0,Brand,Name,Price,Processor_Name,Processor_Brand,RAM_Expandable,RAM,RAM_TYPE,Ghz,Display_type,Display,GPU,GPU_Brand,SSD,HDD,Adapter,Battery_Life
0,0,HP,HP Chromebook 11A-NA0002MU (2E4N0PA) Laptop (1...,22990,MediaTek Octa-core,MediaTek,Not Expandable,4 GB,DDR4 RAM,2.0 Ghz Processor,LED,11.6,Integrated Graphics,MediaTek,64 GB SSD Storage,No HDD,45,Upto 12 Hrs Battery Life
1,1,Lenovo,Lenovo Ideapad Slim 3 (82KU017KIN) Laptop (15....,36289,AMD Hexa-Core Ryzen 5,AMD,12 GB Expandable,8 GB,DDR4 RAM,4.0 Ghz Processor,LCD,15.6,Radeon,AMD,512 GB SSD Storage,No HDD,65,Upto 11 Hrs Battery Life
2,3,Dell,Dell G15-5520 (D560822WIN9B) Laptop (15.6 Inch...,78500,Intel Core i5 (12th Gen),Intel,32 GB Expandable,16 GB,DDR5 RAM,3.3 Ghz Processor,LCD,15.6,"GeForce RTX 3050 GPU, 4 GB",NVIDIA,512 GB SSD Storage,No HDD,56,Upto 10 Hrs Battery Life
3,4,HP,HP 15s-fy5007TU (91R03PA) Laptop (15.6 Inch | ...,55490,Intel Core i5 (12th Gen),Intel,8 GB Expandable,8 GB,DDR4 RAM,4.2 Ghz Processor,LCD,15.6,Iris Xe,Intel,512 GB SSD Storage,No HDD,no,Upto 7.30 Hrs Battery Life
4,6,Infinix,Infinix Inbook Y2 Plus XL29 Laptop (15.6 Inch ...,21990,Intel Core i3 (11th Gen),Intel,Not Expandable,8 GB LP,LPDDR4X RAM,1.7 Ghz Processor,LCD,15.6,UHD,Intel,512 GB SSD Storage,No HDD,45,Upto 8 Hrs Battery Life

In [252]:
c = laptops.columns
c

Index(['Unnamed: 0', 'Brand', 'Name', 'Price', 'Processor_Name',
       'Processor_Brand', 'RAM_Expandable', 'RAM', 'RAM_TYPE', 'Ghz',
       'Display_type', 'Display', 'GPU', 'GPU_Brand', 'SSD', 'HDD', 'Adapter',
       'Battery_Life'],
      dtype='str')

In [253]:
laptops.drop(c[0], axis=1, inplace=True)

In [257]:
laptops.info()

<class 'pandas.DataFrame'>
RangeIndex: 3976 entries, 0 to 3975
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Brand            3976 non-null   str
 1   Name             3976 non-null   str
 2   Price            3976 non-null   float64
 3   Processor_Name   3976 non-null   str
 4   Processor_Brand  3976 non-null   str
 5   RAM_Expandable   3976 non-null   str
 6   RAM              3976 non-null   str
 7   RAM_TYPE         3976 non-null   str
 8   Ghz              3976 non-null   str
 9   Display_type     3976 non-null   str
 10  Display          3976 non-null   str
 11  GPU              3968 non-null   str
 12  GPU_Brand        3972 non-null   str
 13  SSD              3976 non-null   str
 14  HDD              3976 non-null   str
 15  Adapter          3976 non-null   str
 16  Battery_Life     3558 non-null   str
dtypes: float64(1), str(16)
memory usage: 1.6 MB

In [ ]:
# Convert price from indian currency into USD
laptops['Price'] = laptops['Price'] * 0.01

In [259]:
laptops.head(2)

,Brand,Name,Price,Processor_Name,Processor_Brand,RAM_Expandable,RAM,RAM_TYPE,Ghz,Display_type,Display,GPU,GPU_Brand,SSD,HDD,Adapter,Battery_Life
0,HP,HP Chromebook 11A-NA0002MU (2E4N0PA) Laptop (1...,229.90,MediaTek Octa-core,MediaTek,Not Expandable,4 GB,DDR4 RAM,2.0 Ghz Processor,LED,11.6,Integrated Graphics,MediaTek,64 GB SSD Storage,No HDD,45,Upto 12 Hrs Battery Life
1,Lenovo,Lenovo Ideapad Slim 3 (82KU017KIN) Laptop (15....,362.89,AMD Hexa-Core Ryzen 5,AMD,12 GB Expandable,8 GB,DDR4 RAM,4.0 Ghz Processor,LCD,15.6,Radeon,AMD,512 GB SSD Storage,No HDD,65,Upto 11 Hrs Battery Life

In [260]:
laptops.isnull().sum()

Brand                0
Name                 0
Price                0
Processor_Name       0
Processor_Brand      0
RAM_Expandable       0
RAM                  0
RAM_TYPE             0
Ghz                  0
Display_type         0
Display              0
GPU                  8
GPU_Brand            4
SSD                  0
HDD                  0
Adapter              0
Battery_Life       418
dtype: int64

In [ ]:
# laptops.dropna(subset=df.columns.drop('Battery') ,inplace=True)

In [261]:
laptops.to_csv('laptops.csv', index=False)

---

# cars data

In [412]:
# cars data
cars = pd.read_csv('resources/Cars Datasets 2025.csv', encoding='latin1')
cars.head()

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Cars Prices,Fuel Types,Seats,Torque
0,FERRARI,SF90 STRADALE,V8,3990 cc,963 hp,340 km/h,2.5 sec,"$1,100,000",plug in hyrbrid,2,800 Nm
1,ROLLS ROYCE,PHANTOM,V12,6749 cc,563 hp,250 km/h,5.3 sec,"$460,000",Petrol,5,900 Nm
2,Ford,KA+,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,"$12,000-$15,000",Petrol,5,100 - 140 Nm
3,MERCEDES,GT 63 S,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,"$161,000",Petrol,4,900 Nm
4,AUDI,AUDI R8 Gt,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,"$253,290",Petrol,2,560 Nm

In [413]:
cars.rename(columns={'Cars Prices':'Price'}, inplace=True)
cars.head(1)

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Price,Fuel Types,Seats,Torque
0,FERRARI,SF90 STRADALE,V8,3990 cc,963 hp,340 km/h,2.5 sec,"$1,100,000",plug in hyrbrid,2,800 Nm

In [414]:
cars.isnull().sum()

Company Names                0
Cars Names                   0
Engines                      0
CC/Battery Capacity          3
HorsePower                   0
Total Speed                  0
Performance(0 - 100 )KM/H    6
Price                        0
Fuel Types                   0
Seats                        0
Torque                       1
dtype: int64

In [415]:
cars[cars['Price'].str.contains('N')]

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Price,Fuel Types,Seats,Torque
1147,Mazda,RX-Vision Concept,Rotary SkyActiv-R,NaN,400 hp (est.),300 km/h (est.),NaN,N/A (Concept Only),Petrol (Hybrid),2,NaN

In [416]:
len(cars)

1218

In [417]:
cars.drop(1147, inplace=True, )
len(cars)

1217

In [418]:
cars = cars.reset_index(drop=True)

In [419]:
cars[cars['Price'].str.contains('x')]

Empty DataFrame
Columns: [Company Names, Cars Names, Engines, CC/Battery Capacity, HorsePower, Total Speed, Performance(0 - 100 )KM/H, Price, Fuel Types, Seats, Torque]
Index: []

In [421]:
'\x96' in '43590 \x96 48000'

True

In [422]:
cars.loc[1216,:]

Company Names                                      Toyota
Cars Names                                 RAV4 (6th Gen)
Engines                      2.5L Hybrid / Plug-in Hybrid
CC/Battery Capacity                        2487 cc + batt
HorsePower                                   219  302 hp
Total Speed                                      200 km/h
Performance(0 - 100 )KM/H                   6.0  8.1 sec
Price                                   $29,000  $43,000
Fuel Types                               Hybrid / Plug-in
Seats                                                   5
Torque                                       221  400 Nm
Name: 1216, dtype: str

In [423]:
'' in ' $29,000  $43,000'

True

In [424]:
cars['Price'] = cars['Price'].str.replace('','-').str.replace('','').str.replace('\x96','-').str.replace('\x80','-')

In [425]:
for r in range(len(cars)):

    # if '\x96' in cars['Price'][r]:
    #     cars.loc[r,7] = cars['Price'][r].replace('\x96','-')
    # if '\x80' in cars['Price'][r]:
    #     cars.loc[r,7] = cars['Price'][r].replace('\x80','-')
    # if '' in cars['Price'][r]:
    #     cars.loc[r,7] = cars['Price'][r].replace('','-')
        
    if '-' in cars['Price'][r]:
        price1 = int(cars['Price'][r].split('-')[0].replace('$','').replace(',','').strip())
        price2 = int(cars['Price'][r].split('-')[1].replace('$','').replace(',','').strip())
        price = (price1+price2)/2
        cars.iloc[r,7] = str(price)
        # cars['Price'][r] = price
        # print(price)
    elif '/' in cars['Price'][r]:
        price1 = int(cars['Price'][r].split('/')[0].replace('$','').replace(',','').strip())
        price2 = int(cars['Price'][r].split('/')[1].replace('$','').replace(',','').strip())
        price = (price1+price2)/2
        # cars['Price'][r] = price
        cars.iloc[r,7] = str(price)
        # print(price)
    else:
        # try:
        price = int(cars['Price'][r].replace('$','').replace(',','').strip())
        # print(price)
        cars.iloc[r,7] = str(price)

In [426]:
cars.head()

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Price,Fuel Types,Seats,Torque
0,FERRARI,SF90 STRADALE,V8,3990 cc,963 hp,340 km/h,2.5 sec,1100000,plug in hyrbrid,2,800 Nm
1,ROLLS ROYCE,PHANTOM,V12,6749 cc,563 hp,250 km/h,5.3 sec,460000,Petrol,5,900 Nm
2,Ford,KA+,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,13500.0,Petrol,5,100 - 140 Nm
3,MERCEDES,GT 63 S,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,161000,Petrol,4,900 Nm
4,AUDI,AUDI R8 Gt,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,253290,Petrol,2,560 Nm

In [427]:
cars.info()

<class 'pandas.DataFrame'>
RangeIndex: 1217 entries, 0 to 1216
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Company Names              1217 non-null   str
 1   Cars Names                 1217 non-null   str
 2   Engines                    1217 non-null   str
 3   CC/Battery Capacity        1215 non-null   str
 4   HorsePower                 1217 non-null   str
 5   Total Speed                1217 non-null   str
 6   Performance(0 - 100 )KM/H  1212 non-null   str
 7   Price                      1217 non-null   str
 8   Fuel Types                 1217 non-null   str
 9   Seats                      1217 non-null   str
 10  Torque                     1217 non-null   str
dtypes: str(11)
memory usage: 205.1 KB

In [428]:
cars['Price'] = cars['Price'].astype(float)

cars.info()

<class 'pandas.DataFrame'>
RangeIndex: 1217 entries, 0 to 1216
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Company Names              1217 non-null   str
 1   Cars Names                 1217 non-null   str
 2   Engines                    1217 non-null   str
 3   CC/Battery Capacity        1215 non-null   str
 4   HorsePower                 1217 non-null   str
 5   Total Speed                1217 non-null   str
 6   Performance(0 - 100 )KM/H  1212 non-null   str
 7   Price                      1217 non-null   float64
 8   Fuel Types                 1217 non-null   str
 9   Seats                      1217 non-null   str
 10  Torque                     1217 non-null   str
dtypes: float64(1), str(10)
memory usage: 198.6 KB

In [429]:
cars.to_csv('cars.csv', index=False)

---

In [2]:
import pandas as pd
phones = pd.read_csv('mobile_phones.csv')
laptops = pd.read_csv('laptops.csv')
cars = pd.read_csv('cars.csv')

In [3]:
phones.head()

,Company Name,Model Name,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Price,Launched Year
0,Apple,iPhone 16 128GB,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,799.0,2024
1,Apple,iPhone 16 256GB,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,849.0,2024
2,Apple,iPhone 16 512GB,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,899.0,2024
3,Apple,iPhone 16 Plus 128GB,6GB,12MP,48MP,A17 Bionic,"4,200mAh",6.7 inches,899.0,2024
4,Apple,iPhone 16 Plus 256GB,6GB,12MP,48MP,A17 Bionic,"4,200mAh",6.7 inches,949.0,2024

In [4]:
len(phones)

1770

In [5]:
laptops.head()

,Brand,Name,Price,Processor_Name,Processor_Brand,RAM_Expandable,RAM,RAM_TYPE,Ghz,Display_type,Display,GPU,GPU_Brand,SSD,HDD,Adapter,Battery_Life
0,HP,HP Chromebook 11A-NA0002MU (2E4N0PA) Laptop (1...,229.90,MediaTek Octa-core,MediaTek,Not Expandable,4 GB,DDR4 RAM,2.0 Ghz Processor,LED,11.6,Integrated Graphics,MediaTek,64 GB SSD Storage,No HDD,45,Upto 12 Hrs Battery Life
1,Lenovo,Lenovo Ideapad Slim 3 (82KU017KIN) Laptop (15....,362.89,AMD Hexa-Core Ryzen 5,AMD,12 GB Expandable,8 GB,DDR4 RAM,4.0 Ghz Processor,LCD,15.6,Radeon,AMD,512 GB SSD Storage,No HDD,65,Upto 11 Hrs Battery Life
2,Dell,Dell G15-5520 (D560822WIN9B) Laptop (15.6 Inch...,785.00,Intel Core i5 (12th Gen),Intel,32 GB Expandable,16 GB,DDR5 RAM,3.3 Ghz Processor,LCD,15.6,"GeForce RTX 3050 GPU, 4 GB",NVIDIA,512 GB SSD Storage,No HDD,56,Upto 10 Hrs Battery Life
3,HP,HP 15s-fy5007TU (91R03PA) Laptop (15.6 Inch | ...,554.90,Intel Core i5 (12th Gen),Intel,8 GB Expandable,8 GB,DDR4 RAM,4.2 Ghz Processor,LCD,15.6,Iris Xe,Intel,512 GB SSD Storage,No HDD,no,Upto 7.30 Hrs Battery Life
4,Infinix,Infinix Inbook Y2 Plus XL29 Laptop (15.6 Inch ...,219.90,Intel Core i3 (11th Gen),Intel,Not Expandable,8 GB LP,LPDDR4X RAM,1.7 Ghz Processor,LCD,15.6,UHD,Intel,512 GB SSD Storage,No HDD,45,Upto 8 Hrs Battery Life

In [6]:
len(laptops)

3976

In [7]:
cars.head()

,Company Names,Cars Names,Engines,CC/Battery Capacity,HorsePower,Total Speed,Performance(0 - 100 )KM/H,Price,Fuel Types,Seats,Torque
0,FERRARI,SF90 STRADALE,V8,3990 cc,963 hp,340 km/h,2.5 sec,1100000.0,plug in hyrbrid,2,800 Nm
1,ROLLS ROYCE,PHANTOM,V12,6749 cc,563 hp,250 km/h,5.3 sec,460000.0,Petrol,5,900 Nm
2,Ford,KA+,1.2L Petrol,"1,200 cc",70-85 hp,165 km/h,10.5 sec,13500.0,Petrol,5,100 - 140 Nm
3,MERCEDES,GT 63 S,V8,"3,982 cc",630 hp,250 km/h,3.2 sec,161000.0,Petrol,4,900 Nm
4,AUDI,AUDI R8 Gt,V10,"5,204 cc",602 hp,320 km/h,3.6 sec,253290.0,Petrol,2,560 Nm

In [8]:
len(cars)

1217

In [9]:
phones.head(1)

,Company Name,Model Name,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Price,Launched Year
0,Apple,iPhone 16 128GB,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,799.0,2024

In [10]:
phones

,Company Name,Model Name,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Price,Launched Year
0,Apple,iPhone 16 128GB,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,799.00,2024
1,Apple,iPhone 16 256GB,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,849.00,2024
2,Apple,iPhone 16 512GB,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,899.00,2024
3,Apple,iPhone 16 Plus 128GB,6GB,12MP,48MP,A17 Bionic,"4,200mAh",6.7 inches,899.00,2024
4,Apple,iPhone 16 Plus 256GB,6GB,12MP,48MP,A17 Bionic,"4,200mAh",6.7 inches,949.00,2024
...,...,...,...,...,...,...,...,...,...,...
1765,hmd,110 Dual Sim Keypad Phone with Built-in Scan &...,4 MB RAM | 4 MB ROM,NaN,0.2MP Rear Camera,1000 mAh Battery,0,5.08 cm (2 inch) NA Display,11.89,0
1766,vivo,"Y19s 5G (Majestic Green, 64.0 GB)",4 GB RAM | 64.0 GB ROM | Expandable Upto 2 TB,5MP,13MP + 0.08MP,6000 mAh Battery,0,17.12 cm (6.74 inch) Display,124.99,0
1767,MOTOROLA,"Edge 70 (PANTONE Lily Pad, 256 GB)",8 GB RAM | 256 GB ROM,50MP,50MP + 50MP,5000 mAh Battery,0,17.02 cm (6.7 inch) Display,329.99,0
1768,realme,"P3 Ultra 5G (Neptune Blue, 128 GB)",8 GB RAM | 128 GB ROM,16MP,50MP + 8MP,6000 mAh Battery,0,17.35 cm (6.83 inch) Display,239.99,0
1769,Kechaoda,A27,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB,0MP,0MP,800 mAh Battery,0,1.68 cm (0.66 inch) QVGA Display,8.99,0

In [14]:
phones[(phones['Back Camera'].str.contains('\+'))]

,Company Name,Model Name,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Price,Launched Year
6,Apple,iPhone 16 Pro 128GB,6GB,12MP / 4K,50MP + 12MP,A17 Pro,"4,400mAh",6.1 inches,999.00,2024
7,Apple,iPhone 16 Pro 256GB,8GB,12MP / 4K,50MP + 12MP,A17 Pro,"4,400mAh",6.1 inches,1049.00,2024
8,Apple,iPhone 16 Pro 512GB,8GB,12MP / 4K,50MP + 12MP,A17 Pro,"4,400mAh",6.1 inches,1099.00,2024
9,Apple,iPhone 16 Pro Max 128GB,6GB,12MP / 4K,48MP + 12MP,A17 Pro,"4,500mAh",6.7 inches,1099.00,2024
10,Apple,iPhone 16 Pro Max 256GB,8GB,12MP / 4K,48MP + 12MP,A17 Pro,"4,500mAh",6.7 inches,1199.00,2024
...,...,...,...,...,...,...,...,...,...,...
1754,realme,"P3 Pro 5G (Nebula Glow, 128 GB)",8 GB RAM | 128 GB ROM,16MP,50MP + 2MP,6000 mAh Battery,0,17.35 cm (6.83 inch) Display,209.99,0
1762,MOTOROLA,"Signature (PANTONE Carbon, 1 TB)",16 GB RAM | 1 TB ROM,50MP,50MP + 50MP + 50MP,5200 mAh Battery,0,17.27 cm (6.8 inch) Super HD Display,699.99,0
1766,vivo,"Y19s 5G (Majestic Green, 64.0 GB)",4 GB RAM | 64.0 GB ROM | Expandable Upto 2 TB,5MP,13MP + 0.08MP,6000 mAh Battery,0,17.12 cm (6.74 inch) Display,124.99,0
1767,MOTOROLA,"Edge 70 (PANTONE Lily Pad, 256 GB)",8 GB RAM | 256 GB ROM,50MP,50MP + 50MP,5000 mAh Battery,0,17.02 cm (6.7 inch) Display,329.99,0
1768,realme,"P3 Ultra 5G (Neptune Blue, 128 GB)",8 GB RAM | 128 GB ROM,16MP,50MP + 8MP,6000 mAh Battery,0,17.35 cm (6.83 inch) Display,239.99,0

In [76]:
phones

,Company Name,Model Name,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Price,Launched Year
0,Apple,iPhone 16 128GB,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,799.00,2024
1,Apple,iPhone 16 256GB,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,849.00,2024
2,Apple,iPhone 16 512GB,6GB,12MP,48MP,A17 Bionic,"3,600mAh",6.1 inches,899.00,2024
3,Apple,iPhone 16 Plus 128GB,6GB,12MP,48MP,A17 Bionic,"4,200mAh",6.7 inches,899.00,2024
4,Apple,iPhone 16 Plus 256GB,6GB,12MP,48MP,A17 Bionic,"4,200mAh",6.7 inches,949.00,2024
...,...,...,...,...,...,...,...,...,...,...
1765,hmd,110 Dual Sim Keypad Phone with Built-in Scan &...,4 MB RAM | 4 MB ROM,NaN,0.2MP Rear Camera,1000 mAh Battery,0,5.08 cm (2 inch) NA Display,11.89,0
1766,vivo,"Y19s 5G (Majestic Green, 64.0 GB)",4 GB RAM | 64.0 GB ROM | Expandable Upto 2 TB,5MP,13MP + 0.08MP,6000 mAh Battery,0,17.12 cm (6.74 inch) Display,124.99,0
1767,MOTOROLA,"Edge 70 (PANTONE Lily Pad, 256 GB)",8 GB RAM | 256 GB ROM,50MP,50MP + 50MP,5000 mAh Battery,0,17.02 cm (6.7 inch) Display,329.99,0
1768,realme,"P3 Ultra 5G (Neptune Blue, 128 GB)",8 GB RAM | 128 GB ROM,16MP,50MP + 8MP,6000 mAh Battery,0,17.35 cm (6.83 inch) Display,239.99,0
1769,Kechaoda,A27,32 MB RAM | 32 MB ROM | Expandable Upto 16 GB,0MP,0MP,800 mAh Battery,0,1.68 cm (0.66 inch) QVGA Display,8.99,0

In [93]:
s = "samsung-apple-oppo"
companies = []
if s.__contains__('-'):
    companies = s.split('-')
companies

['samsung', 'apple', 'oppo']

In [117]:
def search_phone(budget=0, company='', ram=0, front_camera=0, back_camera=0, multi_cameras=False):
    if budget:
        results = phones[(phones['Price']<=budget)]
    else:
        results = phones
    if company:
        if company.__contains__('-'):
            companies = company.split('-')
            result = pd.DataFrame()
            for c in companies:
                temp = results[(results['Company Name'].str.contains(c.strip(), case=False))]
                result = pd.concat([result,temp])
            results = result
        else:
            results = results[(results['Company Name'].str.contains(company, case=False))]
    if ram:
        # results = results[(results['RAM']>=ram)]
        # if not company.__contains__('apple'):
        results = pd.concat([results[(results['RAM'].str.contains(f"{ram} GB", case=False))],results[(results['RAM'].str.contains(f"{ram}GB", case=False))]])
    if front_camera:
        # results = results[(results['Front Camera']>=front_camera)]
        results = pd.concat([results[(results['Front Camera'].str.contains(f"{front_camera}MP", case=False))],results[(results['Front Camera'].str.contains(f"{front_camera} MP", case=False))]])
    if back_camera:
        # results = results[(results['Back Camera']>=back_camera)]
        # results = results[(results['Back Camera'].str.contains(back_camera, case=False))]
        results = pd.concat([results[(results['Back Camera'].str.contains(f"{back_camera}MP", case=False))],results[(results['Back Camera'].str.contains(f"{back_camera} MP", case=False))]])
    if multi_cameras:
        results = results[(results['Back Camera'].str.contains('\+'))]
    return results

In [118]:
results = search_phone(company='apple-samsung', ram=8, back_camera=8)
results

,Company Name,Model Name,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Price,Launched Year
931,Apple,"iPhone 16 (White, 128 GB)",128 GB ROM,12MP,48MP + 12MP,"A18 Chip, 6 Core Processor Processor",0,15.49 cm (6.1 inch) Super Retina XDR Display,649.00,0
933,Apple,"iPhone 16 (Black, 128 GB)",128 GB ROM,12MP,48MP + 12MP,"A18 Chip, 6 Core Processor Processor",0,15.49 cm (6.1 inch) Super Retina XDR Display,649.00,0
935,Apple,"iPhone 16 (Teal, 128 GB)",128 GB ROM,12MP,48MP + 12MP,"A18 Chip, 6 Core Processor Processor",0,15.49 cm (6.1 inch) Super Retina XDR Display,649.00,0
937,Apple,"iPhone 16 (Ultramarine, 128 GB)",128 GB ROM,12MP,48MP + 12MP,"A18 Chip, 6 Core Processor Processor",0,15.49 cm (6.1 inch) Super Retina XDR Display,649.00,0
941,Apple,"iPhone 16 (Pink, 128 GB)",128 GB ROM,12MP,48MP + 12MP,"A18 Chip, 6 Core Processor Processor",0,15.49 cm (6.1 inch) Super Retina XDR Display,649.00,0
956,Apple,"iPhone 15 (Black, 128 GB)",128 GB ROM,12MP,48MP + 12MP,"A16 Bionic Chip, 6 Core Processor Processor",0,15.49 cm (6.1 inch) Super Retina XDR Display,549.00,0
1034,Apple,"iPhone 15 (Pink, 128 GB)",128 GB ROM,12MP,48MP + 12MP,"A16 Bionic Chip, 6 Core Processor Processor",0,15.49 cm (6.1 inch) Super Retina XDR Display,549.00,0
1052,Apple,"iPhone 16 (Ultramarine, 128 GB)",128 GB ROM,12MP,48MP + 12MP,"A18 Chip, 6 Core Processor Processor",0,15.49 cm (6.1 inch) Super Retina XDR Display,649.00,0
1151,Apple,"iPhone 15 (Pink, 128 GB)",128 GB ROM,12MP,48MP + 12MP,"A16 Bionic Chip, 6 Core Processor Processor",0,15.49 cm (6.1 inch) Super Retina XDR Display,549.00,0
1148,Samsung,"Galaxy A35 5G (Awesome Iceblue, 128 GB)",8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,13MP,50MP + 8MP + 5MP,5000 mAh Battery,0,16.76 cm (6.6 inch) Full HD+ Display,199.99,0
1172,Samsung,"Galaxy F36 5G (Black, 128 GB)",6 GB RAM | 128 GB ROM | Expandable Upto 2 TB,13MP,50MP + 8MP + 2MP,5000 mAh Battery,0,17.02 cm (6.7 inch) Full HD+ Display,159.99,0
1234,Samsung,"Galaxy F36 5G (Violet, 128 GB)",6 GB RAM | 128 GB ROM | Expandable Upto 2 TB,13MP,50MP + 8MP + 2MP,5000 mAh Battery,0,17.02 cm (6.7 inch) Full HD+ Display,159.99,0
1253,Samsung,"Galaxy F36 5G (Black, 128 GB)",8 GB RAM | 128 GB ROM | Expandable Upto 2 TB,13MP,50MP + 8MP + 2MP,5000 mAh Battery,0,17.02 cm (6.7 inch) Full HD+ Display,174.99,0
1317,Samsung,"Galaxy S24 FE 5G (Graphite, 256 GB)",8 GB RAM | 256 GB ROM,10MP,50MP + 12MP + 8MP,4700 mAh Battery,0,17.02 cm (6.7 inch) Full HD+ Display,459.99,0
1318,Samsung,"Galaxy S24 FE 5G (Graphite, 128 GB)",8 GB RAM | 128 GB ROM,10MP,50MP + 12MP + 8MP,4700 mAh Battery,0,17.02 cm (6.7 inch) Full HD+ Display,399.99,0
1437,Samsung,"Galaxy S24 FE 5G (Graphite, 256 GB)",8 GB RAM | 256 GB ROM,10MP,50MP + 12MP + 8MP,4700 mAh Battery,0,17.02 cm (6.7 inch) Full HD+ Display,459.99,0
1440,Samsung,"Galaxy S24 FE 5G (Graphite, 128 GB)",8 GB RAM | 128 GB ROM,10MP,50MP + 12MP + 8MP,4700 mAh Battery,0,17.02 cm (6.7 inch) Full HD+ Display,399.99,0
1461,Samsung,"Galaxy F36 5G (Red, 128 GB)",6 GB RAM | 128 GB ROM | Expandable Upto 2 TB,13MP,50MP + 8MP + 2MP,5000 mAh Battery,0,17.02 cm (6.7 inch) Full HD+ Display,159.99,0
1496,Samsung,"Galaxy S24 FE 5G (Blue, 256 GB)",8 GB RAM | 256 GB ROM,10MP,50MP + 12MP + 8MP,4700 mAh Battery,0,17.02 cm (6.7 inch) Full HD+ Display,459.99,0
1647,Samsung,"Galaxy M56 5G (Light Green, 128 GB)",8 GB RAM | 128 GB ROM,12MP + 2MP Dual,50MP + 50MP + 8MP,5000 mAh Battery,0,17.02 cm (6.7 inch) Full HD+ E3 Super AMOLED D...,218.11,0
1676,Samsung,"Galaxy F36 5G (Red, 128 GB)",8 GB RAM | 128 GB ROM | Expandable Upto 2 TB,13MP,50MP + 8MP + 2MP,5000 mAh Battery,0,17.02 cm (6.7 inch) Full HD+ Display,174.99,0
1695,Samsung,"Galaxy M56 5G (Light Green, 128 GB)",8 GB RAM | 128 GB ROM,12MP + 2MP Dual,50MP + 50MP + 8MP,5000 mAh Battery,0,17.02 cm (6.7 inch) Full HD+ E3 Super AMOLED D...,218.13,0
10,Apple,iPhone 16 Pro Max 256GB,8GB,12MP / 4K,48MP + 12MP,A17 Pro,"4,500mAh",6.7 inches,1199.00,2024
11,Apple,iPhone 16 Pro Max 512GB,8GB,12MP / 4K,48MP + 12MP,A17 Pro,"4,500mAh",6.7 inches,1299.00,2024
19,Apple,iPhone 15 Pro 256GB,8GB,12MP / 4K,48MP + 12MP,A16 Bionic,"4,400mAh",6.1 inches,1199.00,2023
20,Apple,iPhone 15 Pro 512GB,8GB,12MP / 4K,48MP + 12MP,A16 Bionic,"4,400mAh",6.1 inches,1299.00,2023
22,Apple,iPhone 15 Pro Max 256GB,8GB,12MP / 4K,48MP + 12MP,A16 Bionic,"4,500mAh",6.7 inches,1299.00,2023
23,Apple,iPhone 15 Pro Max 512GB,8GB,12MP / 4K,48MP + 12MP,A16 Bionic,"4,500mAh",6.7 inches,1399.00,2023
31,Apple,iPhone 14 Pro 256GB,8GB,12MP / 4K,48MP + 12MP,A16 Bionic,"4,200mAh",6.1 inches,1199.00,2022
32,Apple,iPhone 14 Pro 512GB,8GB,12MP / 4K,48MP + 12MP,A16 Bionic,"4,200mAh",6.1 inches,1299.00,2022
34,Apple,iPhone 14 Pro Max 256GB,8GB,12MP / 4K,48MP + 12MP,A16 Bionic,"4,500mAh",6.7 inches,1299.00,2022
35,Apple,iPhone 14 Pro Max 512GB,8GB,12MP / 4K,48MP + 12MP,A16 Bionic,"4,500mAh",6.7 inches,1399.00,2022
133,Samsung,Galaxy M54 128GB,8GB,32MP,108MP + 8MP,Exynos 1380,6000mAh,6.7 inches,349.00,2023
134,Samsung,Galaxy M54 256GB,8GB,32MP,108MP + 8MP,Exynos 1380,6000mAh,6.7 inches,399.00,2023
141,Samsung,Galaxy F54 128GB,8GB,32MP,108MP + 8MP,Exynos 1380,6000mAh,6.7 inches,349.00,2023
142,Samsung,Galaxy F54 256GB,8GB,32MP,108MP + 8MP,Exynos 1380,6000mAh,6.7 inches,399.00,2023
149,Samsung,Galaxy Note 20 128GB,8GB,10MP,108MP + 12MP,Exynos 990,4300mAh,6.7 inches,999.00,2020
150,Samsung,Galaxy Note 20 256GB,8GB,10MP,108MP + 12MP,Exynos 990,4300mAh,6.7 inches,1099.00,2020
173,Samsung,Galaxy Tab A9+ 128GB,8GB,5MP,8MP,Snapdragon 695,7040mAh,11 inches,229.00,2023

In [116]:
results = search_phone(800, company='apple',multi_cameras=True, back_camera=48)
results

,Company Name,Model Name,RAM,Front Camera,Back Camera,Processor,Battery Capacity,Screen Size,Price,Launched Year
931,Apple,"iPhone 16 (White, 128 GB)",128 GB ROM,12MP,48MP + 12MP,"A18 Chip, 6 Core Processor Processor",0,15.49 cm (6.1 inch) Super Retina XDR Display,649.0,0
933,Apple,"iPhone 16 (Black, 128 GB)",128 GB ROM,12MP,48MP + 12MP,"A18 Chip, 6 Core Processor Processor",0,15.49 cm (6.1 inch) Super Retina XDR Display,649.0,0
935,Apple,"iPhone 16 (Teal, 128 GB)",128 GB ROM,12MP,48MP + 12MP,"A18 Chip, 6 Core Processor Processor",0,15.49 cm (6.1 inch) Super Retina XDR Display,649.0,0
937,Apple,"iPhone 16 (Ultramarine, 128 GB)",128 GB ROM,12MP,48MP + 12MP,"A18 Chip, 6 Core Processor Processor",0,15.49 cm (6.1 inch) Super Retina XDR Display,649.0,0
941,Apple,"iPhone 16 (Pink, 128 GB)",128 GB ROM,12MP,48MP + 12MP,"A18 Chip, 6 Core Processor Processor",0,15.49 cm (6.1 inch) Super Retina XDR Display,649.0,0
956,Apple,"iPhone 15 (Black, 128 GB)",128 GB ROM,12MP,48MP + 12MP,"A16 Bionic Chip, 6 Core Processor Processor",0,15.49 cm (6.1 inch) Super Retina XDR Display,549.0,0
1034,Apple,"iPhone 15 (Pink, 128 GB)",128 GB ROM,12MP,48MP + 12MP,"A16 Bionic Chip, 6 Core Processor Processor",0,15.49 cm (6.1 inch) Super Retina XDR Display,549.0,0
1052,Apple,"iPhone 16 (Ultramarine, 128 GB)",128 GB ROM,12MP,48MP + 12MP,"A18 Chip, 6 Core Processor Processor",0,15.49 cm (6.1 inch) Super Retina XDR Display,649.0,0
1151,Apple,"iPhone 15 (Pink, 128 GB)",128 GB ROM,12MP,48MP + 12MP,"A16 Bionic Chip, 6 Core Processor Processor",0,15.49 cm (6.1 inch) Super Retina XDR Display,549.0,0
1384,Apple,"iPhone 15 (Blue, 256 GB)",256 GB ROM,12MP,48MP + 12MP,"A16 Bionic Chip, 6 Core Processor Processor",0,15.49 cm (6.1 inch) Super Retina XDR Display,649.0,0

---
---